version: "3"

services:
    frontend:
        container_name: frontend
        build: ./frontend
        depends_on:
            - backend
        image: example-frontend
        ports:
          - 5000:5000
    backend:
        container_name: backend
        build: ./backend
        environment:
            REDIS_HOST: redis
        depends_on:
            - redis
        image: example-backend
        ports:
          - 8080:8080
    redis:
        container_name: redis_cache
        image: redis
        restart: unless-stopped