FROM node:16

WORKDIR /usr/src

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

RUN npm install
RUN npm run build
RUN npm install -g serve

CMD ["npx", "serve", "-s", "-l", "5000", "build"]

EXPOSE 5000