services:
    example-frontend:
        image: example-frontend
        container_name: exmaple-frontend
        build: ../example-frontend/
        environment:
            REACT_APP_BACKEND_URL: http://localhost:80
    example-backend:
        image: example-backend
        container_name: backend
        build: ../example-backend/
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
            REQUEST_ORIGIN: http://localhost:80
        depends_on:
            - redis
            - postgres
    redis:
        container_name: redis_cache
        image: redis
        restart: unless-stopped
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
    nginx:
        container_name: nginx
        image: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf